### ISSUE TITLE
Building sandbox on Windows fails

### ISSUE THREAD

**Issue by lxmcf** [lxmcf/virgil-runtime#1]
Using MINGW64 to build the sandbox module fails, looks to be related to linking however everything compiles perfectly on Linux.

Further investigation needed.

**Comment by nlapinski** [comment]
This builds on windows 10 (msys2 using CLANG64 config)

I think it was ```link_with: executable,``` that fixed it, there were a number of errors from missing symbols?
Also valac does a weird things and introduces a different name in the virgil.vapi, it references "Componenet.h" instead of "virgil.h" so I had to delete the virgil header every build.

![image](https://user-images.githubusercontent.com/4634469/219843842-ca5f8be0-e545-4102-adfe-8439bd8a5fed.png)
I cant seem to determin the cause if but I think its happening on repeat builds?

here is my meson.build file - some things changed, mostly to simplify things as testing, I'm theoretically just referring the exe build job for the symbols? and building a shared module. I'm not certain this is the first time I have used meson. I also just link the same dependencies against the .dll/.so

```
project (
    'virgil',  'vala', 'c' ,
    version: '1.0.0',
)

# Compilers
valac = meson.get_compiler ('vala')
cc = meson.get_compiler ('c')


valac_arguments = []

operating_system = build_machine.system ()
if operating_system == 'windows' or operating_system == 'cygwin'
    valac_arguments += '--define=VIRGIL_PLATFORM_WINDOWS'
elif operating_system == 'linux'
    valac_arguments += '--define=VIRGIL_PLATFORM_LINUX'
elif
    valac_arguments += '--define=VIRGIL_PLATFORM_UNKNOWN'
endif

add_project_arguments (valac_arguments, language: 'vala')


dependencies = [
    dependency ('gobject-2.0'),
    dependency ('gmodule-2.0'), # Will include GLIB
    valac.find_library ('raylib', dirs:   meson.current_source_dir () / 'vapi'),
    cc.find_library ('m'),
    cc.find_library ('raylib')
]


add_project_arguments(['--color=always','--enable-experimental', ], language: 'vala')

sources = [
    # PUBLIC API
    'src/Input/KeyCode.vala',
    'src/Input/MouseButton.vala',
    'src/Input/KeyboardInput.vala',
    'src/Input/MouseInput.vala',

    'src/Graphics/Shader.vala',
    'src/Graphics/ShaderDataType.vala',
    'src/Graphics/Font.vala',

    'src/GameObject.vala',
    'src/Component.vala',
    'src/Vector2.vala',
    'src/Rectangle.vala',
    'src/Colour.vala',
    'src/Transform.vala',
    'src/Texture2D.vala',
    'src/RenderTexture.vala',
    'src/Shapes.vala',
    'src/Surface2D.vala',
    'src/Game.vala',

    # PUBLIC COMPONENTS
    'src/Camera2D.vala',
    'src/TextureRenderer.vala',
    'src/Collider2D.vala',
    'src/CircleCollider2D.vala',
    'src/RectangleCollider2D.vala',

    # RUNTIME API
    'src/Runtime/Window.vala',
    'src/Runtime/GameLoader.vala',
    'src/Runtime/Main.vala',
    
]

 executable = executable('virgil',
    sources,
    dependencies: dependencies,
    export_dynamic: true,
    install : true,
    install_dir : meson.current_source_dir ()
  )


game_sources = [
    'sandbox/Game.vala',
    'sandbox/Player.vala',
    'sandbox/Box.vala'
]


game = shared_library('game',
    game_sources,
    dependencies: dependencies,
    link_with: executable,
    name_prefix: '',
    install : true,
    install_dir : meson.current_source_dir ()
)
```

And a little shell script to build

```
rm build/*.h
rm build/*.a
rm build/*.exe
meson setup build
#meson setup build --reconfigure
meson compile -C build
meson install -C build
rm *.a
rm *.exe.a
./virgil.exe --test-build
```

**Comment by nlapinski** [comment]
![image](https://user-images.githubusercontent.com/4634469/219844149-9c8dd3f6-bade-4287-a1a9-a13db3bb0ef2.png)
woo!

**Comment by lxmcf** [comment]
Very interesting... I am not very familiar with Windows when it comes to this but it is almost like -fPIC is being ignored...

Changing the sandbox build to this fixes the issue:
```meson
shared_module (
    'game',

    files (
        'sandbox/Game.vala',
        'sandbox/Player.vala',
        'sandbox/Box.vala'
    ),

    link_with: temp_lib,
    name_prefix: '',

    dependencies: [
        dependency ('gobject-2.0'),
        dependency ('gmodule-2.0'), # Will include GLIB
    ]
)    
```

Unsure how the current state compiles as expected on Linux... Might need to do some more tests in isolation

**Comment by nlapinski** [comment]
Apparently  not from the dll wiki page 🐙:
_Windows does not use [position-independent code](https://en.wikipedia.org/wiki/Position-independent_code) for its DLLs; instead, the code undergoes [relocation](https://en.wikipedia.org/wiki/Relocation_(computing)) as it is loaded, fixing addresses for all its entry points at locations which are free in the memory space of the first process to load the DLL._ 

My hope is meson just sorts this out with the compiler when using share_modules.
I did a quick test running on ubuntu 20 with the changes
```
meson setup build
cd build && ninja
````
all seemed to work, you get the .so + the binary

![image](https://user-images.githubusercontent.com/4634469/219881227-df0d1687-cd60-4c36-b36b-7f42ab260227.png)

**Comment by lxmcf** [comment]
Ah I did not know windows didn't support position independence, goes to show how much I know haha!

Will leave issue open until a cleaner solution comes up.
